### ISSUE TITLE
请问这个sdk能在实际项目使用了吗？

### ISSUE THREAD

**Issue by panjunjie** [arstd/weixin#2]
我项目可能用到该sdk某些功能，请问这个sdk能在实际项目使用了吗？谢谢

**Comment by arstd** [comment]
不好意思，好久没看这个了，这个SDK只是做了一个简单个 HTTP Request 封装，没啥特别的地方，至于是否能使用，看你自己喽。。。

还有，我好久没有开发微信的项目了，所以呢，也没怎么维护了。
